# Generated by Django 4.1 on 2025-06-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_technology_remove_appliedjob_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='jobapplier',
            name='company_name',
        ),
        migrations.AddField(
            model_name='jobapplier',
            name='technologies',
            field=models.ManyToManyField(to='core.technology'),
        ),
    ]
