# Generated by Django 4.2.11 on 2025-06-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_appliedjob_technologies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='job_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jobposting'),
        ),
    ]
